version: "3.9"

services:
  storekeeper-server:
    container_name: storekeeper-server
    env_file: ./.env
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: storekeeper-server:latest
    ports:
      - 8085:8085
    networks:
      network:
        ipv4_address: 10.5.0.2
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
