spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: ${STOREKEEPER_MONGO_URL}
      # host: ${MONGO_HOST}
      # port: ${MONGO_PORT}
      # username: ${USERNAME_MONGO}
      # password: ${PASSWORD_MONGO}
      # database: ${MONGO_DATABASE}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
config:
  openapi:
    title: API (storekeeper)
    description: API Backend storekeeper. Management articles and services for companies. Soon Deliveries.
    terms: https://google.com
    licence: apache 2.0
    licenceUrl: https://google.com
    version: 1.0
    contact:
      name: CBProjects
      url: https://cbprojects.com
      email: contact@cbprojects.com