spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: ${STOREKEEPER_MONGO_URL}
      # uri: mongodb://storekeeper:3F46547XDDPNVjBr@ac-4pi4xp6-shard-00-00.ygkvf6k.mongodb.net:27017,ac-4pi4xp6-shard-00-01.ygkvf6k.mongodb.net:27017,ac-4pi4xp6-shard-00-02.ygkvf6k.mongodb.net:27017/storekeeper-qa?ssl=true&replicaSet=atlas-gne1uu-shard-0&authSource=admin&retryWrites=true&w=majority
      # host: ${MONGO_HOST}
      # port: ${MONGO_PORT}
      # username: ${USERNAME_MONGO}
      # password: ${PASSWORD_MONGO}
      # database: ${MONGO_DATABASE}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
config:
  openapi:
    title: API (storekeeper)
    description: API Backend storekeeper. Management articles and services for companies. Soon Deliveries.
    terms: https://google.com
    licence: apache 2.0
    licenceUrl: https://google.com
    version: 1.0
    contact:
      name: CBProjects
      url: https://cbprojects.com
      email: contact@cbprojects.com

server:
  port: 8443
  servlet:
    context-path: /storekeeper-server
  ssl: 
    key-store: classpath:cbaeneprojects.pfx
    key-store-password: ${SSL_PASSWORD}
    keyStoreType: PKCS12